ergonotes/urls.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Eduardo Augusto Klosowski
#
# This file is part of Ergo Notes.
#
# Ergo Notes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ergo Notes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ergo Notes.  If not, see <http://www.gnu.org/licenses/>.
#

from django.conf.urls import include, url

from . import views


url_list = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^list/$', views.NoteListView.as_view(), name='note_list'),
    url(r'^(?P<pk>\d+)/$', views.NoteDetailView.as_view(), name='note'),
    url(r'^add/$', views.NoteCreateView.as_view(), name='note_add'),
    url(r'^(?P<pk>\d+)/edit/$', views.NoteUpdateView.as_view(), name='note_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.NoteDeleteView.as_view(), name='note_delete'),
    url(r'^(?P<pk>\d+)/changeonhome/$', views.NoteChangeShowOnHomeView.as_view(), name='note_changeonhome'),
    url(r'^(?P<pk>\d+)/export/(?P<format>\w+)/$', views.NoteExportView.as_view(), name='note_export'),
]

urlpatterns = [
    url('', include(url_list, namespace='ergonotes')),
]

ergonotes/models.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Eduardo Augusto Klosowski
#
# This file is part of Ergo Notes.
#
# Ergo Notes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ergo Notes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ergo Notes.  If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.safestring import mark_safe

from . import managers
from .markups import choices_markup, markup_count, markup_function


# Choices

CHOICES_NOTE_MARKUP = [i[:2] for i in choices_markup]

CHOICES_NOTE_PRIORITY = (
    (1, 'Alta'),
    (0, 'Normal'),
    (-1, 'Baixa'),
)


# Models

@python_2_unicode_compatible
class Note(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuário', related_name='+')
    priority = models.SmallIntegerField('prioridade', default=0, choices=CHOICES_NOTE_PRIORITY)
    title = models.CharField('título', max_length=32)
    show_on_home = models.BooleanField('mostrar no home', blank=True, default=False)
    create_on = models.DateTimeField('criado em', auto_now_add=True)
    modify_on = models.DateTimeField('atualizado em', auto_now=True)
    markup = models.CharField('markup', max_length=8, default='txt', choices=CHOICES_NOTE_MARKUP)
    text = models.TextField('texto', blank=True)

    objects = managers.NoteManager()

    class Meta:
        ordering = ('user', '-priority', 'title')
        unique_together = (('user', 'title'),)
        verbose_name = 'nota'
        verbose_name_plural = 'notas'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ergonotes:note', args=(self.pk,))

    def get_count(self):
        return markup_count[self.markup](self.text)

    def get_show_on_home_display(self):
        if self.show_on_home:
            return 'Sim'
        else:
            return 'Não'

    def get_show_on_home_linkdisplay(self):
        return mark_safe('<a href="%s">%s</a>' % (
            reverse('ergonotes:note_changeonhome', args=(self.pk,)),
            self.get_show_on_home_display()
        ))

    def get_text_display(self):
        return markup_function[self.markup](self.text)

ergonotes/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from ergo.foundation.forms import FoundationForm

from . import models


class NoteForm(forms.ModelForm, FoundationForm):
    class Meta:
        fields = ('title', 'priority', 'show_on_home', 'format_type', 'text')
        model = models.Note

        foundation_column_class = {
            'title': 'small-12',
            'priority': 'small-6 medium-4',
            'show_on_home': 'small-6 medium-4',
            'format_type': 'small-12 medium-4',
            'text': 'small-12',
        }

ergonotes/views.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Eduardo Augusto Klosowski
#
# This file is part of Ergo Notes.
#
# Ergo Notes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ergo Notes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ergo Notes.  If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from ergo.views import LoginRequiredMixin
from userviews import views as userviews

from . import models


class IndexView(LoginRequiredMixin, generic.RedirectView):
    permanent = False
    url = reverse_lazy('ergonotes:note_list')


# Note

class NoteListView(LoginRequiredMixin, userviews.UserListView):
    model = models.Note


class NoteDetailView(LoginRequiredMixin, userviews.UserDetailView):
    model = models.Note


class NoteCreateView(LoginRequiredMixin, userviews.UserCreateView):
    model = models.Note
    fields = ('user', 'priority', 'title', 'show_on_home', 'markup', 'text')


class NoteUpdateView(LoginRequiredMixin, userviews.UserUpdateView):
    model = models.Note
    fields = ('priority', 'title', 'show_on_home', 'markup', 'text')


class NoteDeleteView(LoginRequiredMixin, userviews.UserDeleteView):
    model = models.Note
    success_url = reverse_lazy('ergonotes:note_list')


class NoteChangeShowOnHomeView(LoginRequiredMixin, userviews.UserDetailView):
    model = models.Note

    def get(self, request, *args, **kwargs):
        note = self.get_object()
        note.show_on_home = not note.show_on_home
        note.save()

        url = request.META.get('HTTP_REFERER', note.get_absolute_url())
        return HttpResponseRedirect(url)


class NoteExportView(LoginRequiredMixin, userviews.UserDetailView):
    model = models.Note

    def get(self, request, *args, **kwargs):
        note = self.get_object()
        if kwargs.get('format', 'raw') == 'raw':
            content_type = 'text/plain'
            file_type = note.markup
            text = note.text
        else:
            content_type = 'text/html'
            file_type = 'html'
            text = note.get_text_display()

        response = HttpResponse(text, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="%s.%s"' % (note, file_type)
        return response

ergonotes/templates/ergonotes/base.html
{% extends 'ergo/base.html' %}
{% load compress %}
{% load staticfiles %}


{% block title %}{{ block.super }} Notes{% endblock %}

{% block css %}
  {{ block.super }}
  {% compress css %}
    <link rel="stylesheet" href="{% static 'ergonotes/ergonotes.css' %}">
  {% endcompress %}
{% endblock %}

{% block top-bar-left %}
  <ul class="left">
    <li class="divider"></li>
    <li class="has-dropdown">
      <a href="{% url 'ergonotes:note_list' %}">Notas</a>
      <ul class="dropdown">
        <li><a href="{% url 'ergonotes:note_list' %}">Todas</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'ergonotes:note_add' %}">Nova</a></li>
      </ul>
    </li>
    <li class="divider"></li>
  </ul>
{% endblock %}

ergonotes/templates/ergonotes/note_confirm_delete.html
{% extends 'ergonotes/base.html' %}


{% block title %}{{ note }} - {{ block.super }}{% endblock %}


{% block content %}
  <section class="content" role="application">
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="small-12 text-center">
          <h1>Apagar nota "{{ note }}"?</h1>
        </div>
      </div>

      <div class="row">
        <div class="small-12 text-center">
          <a class="button secondary" href="{{ note.get_absolute_url }}">Cancelar</a>
          <button class="alert" type="submit">Apagar</button>
        </div>
      </div>
    </form>
  </section>
{% endblock %}

ergonotes/templates/ergonotes/note_detail.html
{% extends 'ergonotes/base.html' %}


{% block title %}{{ note }} - {{ block.super }}{% endblock %}


{% block content %}
  <section class="content" role="application">
    <div class="row">
      <div class="small-12 columns">
        <h1>{{ note }}</h1>
      </div>
    </div>

    <div class="row">
      <div class="small-12 medium-6 columns">
        <b>Prioridade:</b> {{ note.get_priority_display }}
      </div>
      <div class="small-12 medium-6 columns">
        <b>Markup:</b> {{ note.get_markup_display }}
      </div>
    </div>

    <div class="row">
      <div class="small-12 medium-6 columns">
        <b>Criado em:</b> {{ note.create_on }}
      </div>
      <div class="small-12 medium-6 columns">
        <b>Atualizado em:</b> {{ note.modify_on }}
      </div>
    </div>

    <div class="row">
      <div class="small-12 medium-6 columns">
        <b>Itens:</b> {{ note.get_count|default_if_none:'-' }}
      </div>
      <div class="small-12 medium-6 columns">
        <b>Mostrar no home:</b> {{ note.get_show_on_home_linkdisplay }}
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns small-text-center medium-text-right">
        <a class="button small alert fi-trash" href="{% url 'ergonotes:note_delete' note.pk %}" title="Apagar"></a>
        <a class="button small fi-download" href="{% url 'ergonotes:note_export' note.pk 'raw' %}" title="Expotar"></a>
        <a class="button small fi-page-export" href="{% url 'ergonotes:note_export' note.pk 'html' %}" title="Exportar HTML"></a>
        <a class="button small fi-pencil" href="{% url 'ergonotes:note_edit' note.pk %}" title="Editar"></a>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        {{ note.get_text_display }}
      </div>
    </div>
  </section>
{% endblock %}

ergonotes/templates/ergonotes/note_form.html
{% extends 'ergonotes/base.html' %}
{% load foundation %}


{% block title %}{% if note %}{{ note }}{% else %}Nova Nota{% endif %} - {{ block.super }}{% endblock %}


{% block content %}
  <section class="content" role="application">
    <form method="post">
      {% csrf_token %}
      {% foundation_form_hiddens form %}
      {% foundation_form_errors form %}
      <div class="row">
        <div class="small-12 columns">
          <h1>{{ note|default:'Nova Nota' }}</h1>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          {% foundation_form_field form.title %}
        </div>
      </div>

      <div class="row">
        <div class="small-6 medium-4 columns">
          {% foundation_form_field form.priority %}
        </div>
        <div class="small-6 medium-4 columns">
          {% foundation_form_field form.show_on_home %}
        </div>
        <div class="small-12 medium-4 columns">
          {% foundation_form_field form.markup %}
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          {% foundation_form_field form.text %}
        </div>
      </div>

      <div class="row">
        {% if note %}
          <div class="small-12 medium-6 columns small-text-center medium-text-left">
            <a class="button small alert fi-trash" href="{% url 'ergonotes:note_delete' note.pk %}" title="Apagar"></a>
          </div>
        {% endif %}
        <div class="small-12 {% if note %}medium-6 {% endif %}columns small-text-center medium-text-right">
          <a class="button secondary" href="{% if note %}{{ note.get_absolute_url }}{% else %}{% url 'ergonotes:note_list' %}{% endif %}">Cancelar</a>
          <button type="submit">Salvar</button>
        </div>
      </div>
    </form>
  </section>
{% endblock %}

ergonotes/templates/ergonotes/note_list.html
{% extends 'ergonotes/base.html' %}


{% block title %}Notas - {{ block.super }}{% endblock %}


{% block content %}
  <section class="content" role="application">
    <table class="width-full">
      <thead>
        <tr>
          <th class="width-6r">Prioridade</th>
          <th>Título</th>
          <th class="width-6r show-for-large-up">Mostrar no home?</th>
          <th class="show-for-medium-up">Texto</th>
          <th class="width-6r show-for-large-up">Markup</th>
        </tr>
      </thead>
      <tbody>
        {% for note in note_list %}
          <tr>
            <td>{{ note.get_priority_display }}</td>
            <td><a href="{{ note.get_absolute_url }}">{{ note.title }}</a></td>
            <td class="show-for-large-up">{{ note.get_show_on_home_linkdisplay }}</td>
            <td class="show-for-medium-up"><div class="note-box">{{ note.get_text_display }}</div></td>
            <td class="show-for-large-up">{{ note.get_markup_display }}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </section>
{% endblock %}

ergonotes/templates/ergonotes/pag_note_form.html
{% extends 'ergonotes/base.html' %}
{% load foundation %}
{% load i18n %}


{% block content %}
  <section role="application" class="content">
    <form method="post">
      {% csrf_token %}
      {{ form.as_foundation }}
      <div class="row">
        {% if note %}
          <div class="small-12 medium-6 columns small-text-center medium-text-left">
            <a class="button alert" href="{% url 'ergonotes:note_delete' note.pk %}">{% trans 'Delete' %}</a>
            <a class="button secondary" href="{% url 'ergonotes:note_export' note.pk %}">{% trans 'Export' %}</a>
          </div>
        {% endif %}
        <div class="small-12 {% if note %}medium-6 {% endif %}columns end small-text-center medium-text-right">
          <a class="button secondary" href="{% url 'ergonotes:note_list' %}">{% trans 'Cancel' %}</a>
          <button type="submit">{% trans 'Save' %}</button>
        </div>
      </div>
    </form>
  </section>
{% endblock %}